version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432