version: '3.8'

services:

  fileservice:
    build:
      context: ./src/Services/FileService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network

networks:
  my-network:
