version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: alex
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql